### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Sehktel** [LIDJEN/Disassembler-keil#1]
```
Traceback (most recent call last):
  File "G:\Downloads\Decompiler-main\Decompiler\main.py", line 586, in <module>
    asm_out=bin_2_asm(input_file("bin_input"))
  File "G:\Downloads\Decompiler-main\Decompiler\main.py", line 43, in bin_2_asm
    for j in range(int(bytes.get(sort[i])[-1])):
TypeError: 'NoneType' object is not subscriptable

```

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32.

**Comment by Sehktel** [comment]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32.
